In [5]:
from numpy import *
from matplotlib.pyplot import *
from random import *
%matplotlib tk


In [6]:
# Matching Gaussian
Np = 50000
Nf = 100
Px = zeros(Np)
CONST = 1
P = zeros((Np, CONST * Nf))
for time in range(CONST * Nf):
    for p in range(Np):
        R = random()
        """if R <= 0.5:
            Px[p] = Px[p] + 1
        else:
            Px[p] = Px[p] - 1"""
        if R <= 1/3:
            Px[p] = Px[p]+1
        elif R > 1/3 and R <= 2/3:
            Px[p] = Px[p]-1
        else:
            Px[p] = Px[p]
    P[:, time] = Px
    avePx = mean(Px)
    varPx = mean(Px*Px) - avePx**2


In [8]:
# Distribution
# using normal distribution
# we want to check wether this random distribution is # same as Gaussian
Ds = zeros((2*Nf + 1, CONST * Nf))
print(Ds.shape)
print(linspace(-Nf, Nf, 2 * Nf+1).shape)
In = P + Nf
print(In, shape(In))
In = In.astype('int')
for k in range(CONST * Nf):
    for j in range(Np):
        Ds[In[j, k], k] = Ds[In[j, k], k] + 1
    clf()
    mu = sum(P[:, k])/Np
    varPx = sum(P[:, k]**2)/Np - mu**2
    sig = sqrt(varPx)
    xi = linspace(-Nf, Nf, 1000)
    f = 1/sig/sqrt(2*pi)*exp(-0.5*((xi-mu)/sig)**2)
    plot(linspace(-Nf, Nf, 2 * Nf+1),
         Ds[:, k]/Np, 'm.', label='approximation')
    plot(xi, f, '-b', label='exact')
    #axis((-Nf, Nf, 0, 0.5))
    title("3-choice walk")
    legend()
    pause(0.01)


(201, 100)
(201,)
[[100. 100. 101. ...  93.  94.  95.]
 [100. 101. 102. ... 116. 116. 117.]
 [100.  99.  98. ...  84.  83.  82.]
 ...
 [100. 101. 101. ...  92.  93.  94.]
 [101. 102. 101. ... 100.  99.  99.]
 [100. 100.  99. ... 105. 105. 105.]] (50000, 100)
